### ISSUE TITLE
gluon-config-mode-ppa: Include a second box for the Freifunk-MoU

### ISSUE THREAD

**Issue by Adorfer** [freifunk-kiel/ffki-packages#16]
I would like to let the people setting up nodes have at least the chance to read what Freifunk should be about. 
So this is a feature request, to make it configurable via site.conf to have a checkbox to either accept ppa or  mou ( 2 boxes which have to be both crossed)

https://github.com/freifunk/MoU

**Comment by rubo77** [comment]
duplicate #17
